In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../00_data/07_combined_clean_no_norm.csv")

In [3]:
df

,chain,category_clean,item_name,serve_size,serve_size_unit,nutrition_indicator,value_per_serving
0,McDondalds,beverage,Vanilla Shake (Small),"340,96",ml,calories_kcal,530
1,McDondalds,beverage,Vanilla Shake (Small),"340,96",ml,total_fat_g,15
2,McDondalds,beverage,Vanilla Shake (Small),"340,96",ml,saturated_fat_g,10
3,McDondalds,beverage,Vanilla Shake (Small),"340,96",ml,trans_fat_g,1
4,McDondalds,beverage,Vanilla Shake (Small),"340,96",ml,cholesterol_mg,60
...,...,...,...,...,...,...,...
5775,Subway,beverage,Coca-Cola Classic (Child),"340,96",ml,sodium_mg,0
5776,Subway,beverage,Coca-Cola Classic (Child),"340,96",ml,carbohydrates_g,28
5777,Subway,beverage,Coca-Cola Classic (Child),"340,96",ml,dietary_fiber_g,0
5778,Subway,beverage,Coca-Cola Classic (Child),"340,96",ml,sugars_g,28
5779,Subway,beverage,Coca-Cola Classic (Child),"340,96",ml,protein_g,0

In [4]:
df = df.loc[df["nutrition_indicator"] != "trans_fat_g"]

In [5]:
df

,chain,category_clean,item_name,serve_size,serve_size_unit,nutrition_indicator,value_per_serving
0,McDondalds,beverage,Vanilla Shake (Small),"340,96",ml,calories_kcal,530
1,McDondalds,beverage,Vanilla Shake (Small),"340,96",ml,total_fat_g,15
2,McDondalds,beverage,Vanilla Shake (Small),"340,96",ml,saturated_fat_g,10
4,McDondalds,beverage,Vanilla Shake (Small),"340,96",ml,cholesterol_mg,60
5,McDondalds,beverage,Vanilla Shake (Small),"340,96",ml,sodium_mg,160
...,...,...,...,...,...,...,...
5775,Subway,beverage,Coca-Cola Classic (Child),"340,96",ml,sodium_mg,0
5776,Subway,beverage,Coca-Cola Classic (Child),"340,96",ml,carbohydrates_g,28
5777,Subway,beverage,Coca-Cola Classic (Child),"340,96",ml,dietary_fiber_g,0
5778,Subway,beverage,Coca-Cola Classic (Child),"340,96",ml,sugars_g,28
5779,Subway,beverage,Coca-Cola Classic (Child),"340,96",ml,protein_g,0

In [6]:
# deleted the rows including "nutrition_indicator" = "trans_fat" --> because the WHO data does not include the information.

In [7]:
df.to_csv("../00_data/08_combined_data.csv", index=False)

# ATTENTION: 

### Data has been cleaned in excel. 
- For McDonalds salad sauces, the Cholesterol value has been set to 0, as no value available.
- For subway Kidsmenue, the Cholesterol value has been set to 0, as no value available.

---> Version to be used: 08_01_combined_data_excel_cleaned.csv